name: CI Tests
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: openjdk:11.0
    steps:
    - uses: actions/checkout@v3.5.0
    - name: Run CI tests
      run: mvn package -Dmaven.test.skip=true
