name: luthersystems/shiroclient-sdk-java/luthersystems/shiroclient-sdk-java
on:
  push:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: openjdk:11.0
    steps:
    - uses: actions/checkout@v3.5.0
    - run: mvn package -Dmaven.test.skip=true
